# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_arcgisplaces_wrappers", use_symbols = TRUE, package_name = "arcgisplaces")

#' @usage NULL
#' @useDynLib arcgisplaces, .registration = TRUE
NULL

places_within_extent <- function(xmin, ymin, xmax, ymax, token) .Call(wrap__places_within_extent, xmin, ymin, xmax, ymax, token)

#' Parse /categories/{categoryId} results vectorized
#' @keywords internal
parse_category_details <- function(x) .Call(wrap__parse_category_details, x)

near_point_ <- function(x, y, radius, category_id, search_text, token) .Call(wrap__near_point_, x, y, radius, category_id, search_text, token)


# nolint end
