# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_arcgisplaces_wrappers", use_symbols = TRUE, package_name = "arcgisplaces")

#' @usage NULL
#' @useDynLib arcgisplaces, .registration = TRUE
NULL

parse_categories <- function(x) .Call(wrap__parse_categories, x)

#' Parse `/categories/{categoryId}` results vectorized
#' @keywords internal
parse_category_details <- function(x) .Call(wrap__parse_category_details, x)

near_point_ <- function(x, y, radius, category_id, search_text, token) .Call(wrap__near_point_, x, y, radius, category_id, search_text, token)

parse_place_details <- function(x) .Call(wrap__parse_place_details, x)

places_within_extent <- function(search_text, category_ids, icon, xmin, ymin, xmax, ymax, token, places_url) .Call(wrap__places_within_extent, search_text, category_ids, icon, xmin, ymin, xmax, ymax, token, places_url)


# nolint end
